const express = require("express");
const { requireAuth, requireFreshAdminSession } = require("../middlewares/auth");
const { requireRole } = require("../middlewares/roles");
const ctrl = require("../controllers/adminController");

const router = express.Router();
router.use(requireAuth, requireRole("ADMIN"), requireFreshAdminSession);
router.get("/", ctrl.dashboard);
router.get("/logs", ctrl.logsPage);
router.get("/stats", ctrl.stats);
router.get("/products", ctrl.productsPage);
router.post("/products", ...ctrl.productValidators, ctrl.createProduct);
router.post("/products/:id", ...ctrl.productValidators, ctrl.updateProduct);
router.post("/products/:id/images", ctrl.addProductImage);
router.post("/products/:id/images/:imageId", ctrl.updateProductImage);
router.post("/products/:id/images/:imageId/delete", ctrl.deleteProductImage);
router.post("/products/:id/variants", ctrl.addProductVariant);
router.post("/products/:id/variants/:variantId", ctrl.updateProductVariant);
router.post("/products/:id/variants/:variantId/delete", ctrl.deleteProductVariant);
router.post("/products/:id/delete", ctrl.deleteProduct);
router.get("/categories", ctrl.categoriesPage);
router.post("/categories", ...ctrl.categoryValidators, ctrl.createCategory);
router.post("/categories/:id", ...ctrl.categoryValidators, ctrl.updateCategory);
router.post("/categories/:id/delete", ctrl.deleteCategory);
router.get("/orders", ctrl.ordersPage);
router.get("/orders/:id", ctrl.orderDetailPage);
router.get("/orders/:id/export-pdf", ctrl.orderRawPdf);
router.get("/orders/:id/shipping-label", ctrl.orderShippingLabelPdf);
router.post("/orders/:id/status", ctrl.updateOrder);
router.get("/coupons", ctrl.couponsPage);
router.post("/coupons", ...ctrl.couponValidators, ctrl.createCoupon);
router.get("/reviews", ctrl.reviewsPage);
router.post("/reviews/:id/moderation", ctrl.moderateReview);
router.get("/refunds", ctrl.refundsPage);
router.get("/users", ctrl.usersPage);
router.post("/users/:id/block-toggle", ctrl.toggleUserBlock);
router.get("/logistics", ctrl.logisticsPage);

module.exports = router;
